---
title: "Basic Regression Analysis with Timer Series data"
author: "Jørn I. Halvorsen"
date: "`r Sys.Date()`"
###output:
###  html_notebook:
###    toc: yes
output:
  xaringan::moon_reader:
    lib_dir: libs
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
tasklist: check path rstudio/R, toc, new png for repo, ??, ref
---


```{r xaringan-tile-view, echo=FALSE, message=F, warning=F}
library(xaringan)
xaringanExtra::use_editable(expires = 1)
xaringanExtra::use_tile_view()
#xaringanExtra::use_share_again()
xaringanExtra::use_scribble()
xaringanExtra::use_webcam()
#xaringanExtra::use_slide_tone()
xaringanExtra::use_panelset()
```

```{r, eval=F, include=F}
filen <- "JIH_slides_learning_objectives.Rmd"
xaringan::inf_mr(filen)
rmarkdown::render(filen)
system("brave presentations.html")
servr::daemon_stop()
`
```{r echo=FALSE, results='asis'}
# knit the first three lines of first.Rmd
cat(knitr::knit_child(text = readLines('learning_objectives.Rmd')[30:913]), sep = '\n')
```



